const taskList = document.querySelector('#task__list');
// const answers = JSON.parse(tasks);

const firstScreen = document.querySelector('.first-screen');
const gameRow = document.querySelector('.game-row');
const gameCard = document.querySelector('.gameCard');
const countdownRow = document.querySelector('.row-countdown');
const countdownSpan = document.querySelector('.countdown');
const startButton = document.querySelector('#start_button');
const finishButton = document.querySelector('#finish_button');
const finishCol = document.querySelector('.col-finish');
const playerCount = document.querySelector('#playerCount');
const answerCount = document.querySelector('#answerCount');
const timeCount = document.querySelector('#timeCount');
const settingLink = document.querySelector('.setting-link');
const title = document.querySelector('.gameTitle');
const dropdownMenu = document.querySelector('.dropdown-menu');
const dropdownLink = document.querySelector('.dropdown-toggle');
const reset = document.querySelector('#reset_button')
const resetCol = document.querySelector('.col-reset')
const addTime = document.querySelector('.additional_time');
